# Generated by Django 5.2 on 2025-04-20 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='enter',
            name='product',
        ),
        migrations.RemoveField(
            model_name='out',
            name='product',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Enter',
        ),
        migrations.DeleteModel(
            name='Out',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
